spring.application.name=api-gateway
server.port=8090

spring.cloud.gateway.server.webmvc.routes[0].id=core-auth
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8080
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.server.webmvc.routes[1].id=core-establecimientos
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8080
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/establecimientos/**

spring.cloud.gateway.server.webmvc.routes[2].id=core-notificaciones
spring.cloud.gateway.server.webmvc.routes[2].uri=http://localhost:8080
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/notificaciones/**

spring.cloud.gateway.server.webmvc.routes[3].id=core-dashboard
spring.cloud.gateway.server.webmvc.routes[3].uri=http://localhost:8080
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/dashboard/**

spring.cloud.gateway.server.webmvc.routes[4].id=listas-service
spring.cloud.gateway.server.webmvc.routes[4].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/api/listas/**

spring.cloud.gateway.server.webmvc.routes[5].id=citas-service
spring.cloud.gateway.server.webmvc.routes[5].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/api/citas/**

spring.cloud.gateway.server.webmvc.routes[6].id=pacientes-service
spring.cloud.gateway.server.webmvc.routes[6].uri=http://localhost:8083
spring.cloud.gateway.server.webmvc.routes[6].predicates[0]=Path=/api/pacientes/**

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always